### ISSUE TITLE
TR Rando Enemies issue

### ISSUE THREAD

**Issue by Scorpios9472** [LostArtefacts/TR-Rando#433]
when I launch the randomizer for TR 1 it works fine enough until I try add random enemies and then it pops up with a window saying Object reference not set to an instance of an object. with the details expanded with this: System.NullReferenceException: Object reference not set to an instance of an object.
   at TRRandomizerCore.Randomizers.TR1EnemyRandomizer.RandomizeMeshes(TR1CombinedLevel level, List`1 availableEnemies)
   at TRRandomizerCore.Randomizers.TR1EnemyRandomizer.RandomizeEnemies(TR1CombinedLevel level, EnemyRandomizationCollection enemies)
   at TRRandomizerCore.Randomizers.TR1EnemyRandomizer.EnemyProcessor.ApplyRandomization()
   at TRRandomizerCore.Randomizers.TR1EnemyRandomizer.RandomizeEnemiesCrossLevel()
   at TRRandomizerCore.Randomizers.TR1EnemyRandomizer.Randomize(Int32 seed)
   at TRRandomizerCore.Editors.TR1RandoEditor.SaveImpl(AbstractTRScriptEditor scriptEditor, TRSaveMonitor monitor)
   at TRGE.Coord.AbstractTRLevelEditor.Save(AbstractTRScriptEditor scriptEditor, TRSaveMonitor monitor)
   at TRGE.Coord.TREditor.Save()
--- End of stack trace from previous location where exception was thrown ---
   at TRGE.Coord.TREditor.Save()
   at TRRandomizerView.Windows.RandomizeProgressWindow.Randomize()
   
If I understood what this meant I could then solve my own issue, but I feel that maybe some files are missing from a certain location and I am unaware of what if it is that there is a file missing, but surely it wouldn't run otherwise. I am hoping that maybe someone could help clarify/Translate what it is that is happening ? 

if you could advise me through step by step guidelines of what to do, it would be most appreciative :) Thank you

**Comment by lahm86** [comment]
It sounds like unclean level files, so a complete reinstall is best.
1. Pick File > Empty recent folder list in the randomizer (super important step).
2. Uninstall TR1 and Tomb1Main.
3. Reinstall from scratch following https://youtu.be/WfyHin4Hpgs

**Comment by Scorpios9472** [comment]
Thank you so much for your rapid response, since I have not used the
installer and instead had to resort to the zip, will I just do the same
process but with the zip file?

The reason behind that was the installer was not opening for me, I'm
thinking it's something on my end but I've tried everything to allow the
file to be used and still nothing but that's a separate issue which is okay
😂

I appreciate you again thank you I will try this method

**Comment by lahm86** [comment]
No problem. For the Tomb1Main installer, you will need .NET Core 6 - you can pick the suitable Desktop Runtime for your machine below.
https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by Scorpios9472** [comment]
I will try this, thank you so much for your patience and time :)

**Comment by Scorpios9472** [comment]
Hey so I tried the step by step to a T, and while it has cleaned everything
because The installer is not working for me, I have to use the zip file,
can you tell where I will have to look or what file it is for the Enemies,
if I input it into the directory it should help with the Random Enemies
working, everything else on the randomizer works except the Random enemies

**Comment by lahm86** [comment]
Everything like this is in and taken from the level files, it's not that different parts of the game are stored separately. Which TR1 version are you sourcing the level files from? E.g. Steam or GOG

**Comment by Scorpios9472** [comment]
Well I have the levels sourced from TombATI since Steam doesnt have a clear
spot for the levels and it doesnt contain all of them in a space where I
can find them all together

**Comment by lahm86** [comment]
Ok, and those files are clean as such, as in they've never been modded by another tool? And when you reinstalled, did you also reinstall TombATI to get the clean level files again (otherwise they will still be in a randomized state if you are using the same directory). If you want to, you can send a few of the levels here via zip and I can test them.

**Comment by Scorpios9472** [comment]
CAT.PHD
<https://drive.google.com/file/d/12cWkPREsCpMs9pefbKG07qGC5LBACA1P/view?usp=drive_web>
 CRED0.PCX
<https://drive.google.com/file/d/1ihZ4Zh2YUOhIfBhAJdFQOHYb4v3xGv7h/view?usp=drive_web>
 CRED1.PCX
<https://drive.google.com/file/d/17DV7e32liwjpGWOjwu386Vqxp6EjSSLi/view?usp=drive_web>
 CRED2.PCX
<https://drive.google.com/file/d/1V4VO_p4_f7WTktndtgUhMd5bXzo0zadT/view?usp=drive_web>
 CRED3.PCX
<https://drive.google.com/file/d/1DEoyAz2ukP8PIC0GsC2s_qu1mDLnOgTF/view?usp=drive_web>
 CUT1.PHD
<https://drive.google.com/file/d/1TxGtwNeplkJfUVA6bbAKI7MII8zSMIWL/view?usp=drive_web>
 CUT2.PHD
<https://drive.google.com/file/d/1G5CM_gBdK54xcEtvoTJIt6gIftsJ4NCY/view?usp=drive_web>
 CUT3.PHD
<https://drive.google.com/file/d/1m6QYkXF_vzY82H0aUcHFAewojziDkfTM/view?usp=drive_web>
 CUT4.PHD
<https://drive.google.com/file/d/1sS1_Qo5pwuMevFQRMktuv_0Wfab_qDtD/view?usp=drive_web>
 EGYPT.PHD
<https://drive.google.com/file/d/1y5RoqpWapxapp0pDyFYmrbXbgYSoDUdn/view?usp=drive_web>
 EIDOSPC.PCX
<https://drive.google.com/file/d/1vjCcSteHVyX0PqeAYxxAB9SpF7dd_EDq/view?usp=drive_web>
 END2.PHD
<https://drive.google.com/file/d/1QNnHuAl1de5Uziz-WNk-Hk_0j20nBQO2/view?usp=drive_web>
 END.PCX
<https://drive.google.com/file/d/19yhBmVBsT7NBSpUst7OBntSgpn2ddEWE/view?usp=drive_web>
 END.PHD
<https://drive.google.com/file/d/1gwcel0ocI6KsuWdNLWGToapm2TUO_S3O/view?usp=drive_web>
 GYM.PHD
<https://drive.google.com/file/d/1i7XKy1a2JK2atTB4BqCk4XlEMTO7yapH/view?usp=drive_web>
 INSTALL.PCX
<https://drive.google.com/file/d/1ucSGekxfNgcXlrBD3pY3cumjvLUZ4OM4/view?usp=drive_web>
 LEVEL1.PHD
<https://drive.google.com/file/d/11FyrDs8oieKMri1FMhGL7yJXWnODvWW9/view?usp=drive_web>
 LEVEL2.PHD
<https://drive.google.com/file/d/1wikXAbbqLUOmrHm8zw3PMYIT5l7u88lv/view?usp=drive_web>
 LEVEL3A.PHD
<https://drive.google.com/file/d/1Py4VEk7vG-lyIIJ479v6pXlKIWSQWx3V/view?usp=drive_web>
 LEVEL3B.PHD
<https://drive.google.com/file/d/1N90XInB_rK5CyMmjiuyD9J3WzP0WAxJf/view?usp=drive_web>
 LEVEL4.PHD
<https://drive.google.com/file/d/1CRHuHJcJJD-5GtItcGZumBFA095H83pa/view?usp=drive_web>
 LEVEL5.PHD
<https://drive.google.com/file/d/1uNhiTdz-gTplxLdYh8YOKPYG3bxLaLWe/view?usp=drive_web>
 LEVEL6.PHD
<https://drive.google.com/file/d/14JSHvstPsbin_RDIfCOWkhSEAnOrvpS2/view?usp=drive_web>
 LEVEL7A.PHD
<https://drive.google.com/file/d/1-aRe2NYhIudftqJ7QxqB89u7QjigXFTF/view?usp=drive_web>
 LEVEL7B.PHD
<https://drive.google.com/file/d/1oG6S9nbXJF3TRCM3npLf9MeWOSmpXhKz/view?usp=drive_web>
 LEVEL8A.PHD
<https://drive.google.com/file/d/1CSowVTQuEPNAOvAkWYoNjV_PQ6JoI8f7/view?usp=drive_web>
 LEVEL8B.PHD
<https://drive.google.com/file/d/159XcldaDSIkC59Z_Z0eLdijV_ab23GAZ/view?usp=drive_web>
 LEVEL8C.PHD
<https://drive.google.com/file/d/1I0a3_1J0dA7JGaQMJGAsmmW2B19BuhmU/view?usp=drive_web>
 LEVEL10A.PHD
<https://drive.google.com/file/d/12n-OKVi8JkG4IJrPqxNlwxHGXZdiXUWn/view?usp=drive_web>
 LEVEL10B.PHD
<https://drive.google.com/file/d/1UqRrPP9LX48AQLyY9M4NKBvoAVgfEXgM/view?usp=drive_web>
 LEVEL10C.PHD
<https://drive.google.com/file/d/15AUNgamhr1Qagu_fSPqTTKwBzLbqirUO/view?usp=drive_web>
 TITLE.PHD
<https://drive.google.com/file/d/13m2Fugka3ja_guuQrqsSKULLQ4tZZcys/view?usp=drive_web>
 TITLEH.PCX
<https://drive.google.com/file/d/1MPcYeRu0_KUGjdvpGaDcjzCq0nySJ4Vf/view?usp=drive_web>
So When I install TombATI I put it separate to all the important files so
it doesnt affect My clean Install from Steam, by creating a copy of the
game. I then take the levels from the data file it creates when you combine
the copy of the steam game with TombATI to the current Data directory which
is the one I use for the Tomb1Main etc

I can send you the files here as they come if you want and you can test
them as you said

**Comment by lahm86** [comment]
I don't have access to those files unfortunately, but here are some things to try:

* Make another clean Tomb1Main folder but name it something completely different you haven't used before e.g. `C:\Games\T1MRandoTest`. This will ensure the rando isn't using any cached (and potentially unclean) data files.
* Try randomizing with enemies enabled again, but untick the `Swap enemy appearances` checkbox. The original error is being generated in the code that handles this part.

**Comment by Scorpios9472** [comment]
I will try this and Thank you once again I shall report back with either
good or bad news lol

**Comment by Scorpios9472** [comment]
So after doing what you have said, the problem of the enemies still
persists. however there was one problem, I did not see an option for
untick the Swap enemy appearances checkbox.

**Comment by Scorpios9472** [comment]
I hope this is okay if not then I might have sent it correctly.

**Comment by lahm86** [comment]
Thanks, but it doesn't look like the attachment came through if there was one unfortunately.

**Comment by Scorpios9472** [comment]
Gmail scanned it and was basically telling me it was incase of malware, let
me try this again lol

**Comment by Scorpios9472** [comment]
Hopefully this has done justice

**Comment by lahm86** [comment]
Unfortunately not. Could you try attaching the file directly to the issue in GitHub rather than via Gmail?

**Comment by Scorpios9472** [comment]
[20230323_141757.zip](https://github.com/LostArtefacts/TR-Rando/files/11065591/20230323_141757.zip)
alright this should work now

**Comment by lahm86** [comment]
Thanks, got it. The file contains checksums of your level files, and these do not match what is expected by the randomizer i.e. they're not original as far as the randomizer is concerned, so it's coming across unexpected data and hence the error.

The Steam files definitely work, so I think there are backed up file issues still causing problems. I can only suggest to delete your randomizer backups (use File > Empty recent folder list or browse to `%localappdata%` on your PC and delete the `TRGE` folder altogether). I would also recommend deleting the game folders altogether before you attempt a completely fresh reinstall via Steam, then TombATI. Ideally though, the Tomb1Main installer would be better - were you able to install .NET Core Desktop?

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.15-windows-x64-installer

**Comment by Scorpios9472** [comment]
I did install .NET and if by deleting TRGE then I'll try that and do the
process from scratch and see how it goes

**Comment by Scorpios9472** [comment]
I'll just add something that I may not have mentioned before, so initially
everything was working apart from a select few features of the Randomizer,
the most notable was the level randomizer so I was trying to find ways to
fix it, I found my solution and then the random enemies wasnt working so I
was at a loss at that point so now doing this process might help both cases
hopefully.
